# Generated by Django 5.0.2 on 2024-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
